const hanja_data = {
    "1과": [
        {"hanja": "漢", "meaning": "한나라", "reading": "한"},
        {"hanja": "字", "meaning": "글자", "reading": "자"},
        {"hanja": "文", "meaning": "글월", "reading": "문"},
        {"hanja": "學", "meaning": "배우다", "reading": "학"},
        {"hanja": "校", "meaning": "학교", "reading": "교"},
        {"hanja": "自", "meaning": "스스로", "reading": "자"},
        {"hanja": "己", "meaning": "몸, 자기", "reading": "기"},
        {"hanja": "家", "meaning": "집", "reading": "가"},
        {"hanja": "族", "meaning": "겨레", "reading": "족"},
        {"hanja": "世", "meaning": "세상", "reading": "세"},
        {"hanja": "界", "meaning": "지경", "reading": "계"},
        {"hanja": "然", "meaning": "그러하다", "reading": "연"},
        {"hanja": "話", "meaning": "말씀", "reading": "화"},
        {"hanja": "者", "meaning": "사람", "reading": "자"},
        {"hanja": "光", "meaning": "빛", "reading": "광"},
        {"hanja": "合", "meaning": "합하다", "reading": "합"},
        {"hanja": "成", "meaning": "이루다", "reading": "성"},
        {"hanja": "分", "meaning": "나누다", "reading": "분"},
        {"hanja": "子", "meaning": "아들", "reading": "자"},
        {"hanja": "母", "meaning": "어머니", "reading": "모"},
        {"hanja": "形", "meaning": "모양", "reading": "형"},
        {"hanja": "音", "meaning": "소리", "reading": "음"},
        {"hanja": "義", "meaning": "옳다, 뜻", "reading": "의"},
        {"hanja": "魚", "meaning": "물고기", "reading": "어"},
        {"hanja": "天", "meaning": "하늘", "reading": "천"},
        {"hanja": "地", "meaning": "땅", "reading": "지"},
        {"hanja": "貝", "meaning": "조개", "reading": "패"},
        {"hanja": "肉", "meaning": "고기", "reading": "육"},
        {"hanja": "衣", "meaning": "옷", "reading": "의"},
        {"hanja": "廣", "meaning": "넓다", "reading": "광"},
        {"hanja": "圖", "meaning": "그림", "reading": "도"},
        {"hanja": "兩", "meaning": "둘", "reading": "량"},
        {"hanja": "齒", "meaning": "이", "reading": "치"}
    ],
    "2과": [
        {"hanja": "大", "meaning": "크다", "reading": "대"},
        {"hanja": "韓", "meaning": "나라 이름", "reading": "한"},
        {"hanja": "民", "meaning": "백성", "reading": "민"},
        {"hanja": "國", "meaning": "나라", "reading": "국"},
        {"hanja": "順", "meaning": "순하다, 따르다", "reading": "순"},
        {"hanja": "序", "meaning": "차례", "reading": "서"},
        {"hanja": "口", "meaning": "입", "reading": "구"},
        {"hanja": "筆", "meaning": "붓", "reading": "필"},
        {"hanja": "源", "meaning": "근원", "reading": "원"},
        {"hanja": "則", "meaning": "법칙", "reading": "칙"},
        {"hanja": "三", "meaning": "셋", "reading": "삼"},
        {"hanja": "川", "meaning": "내", "reading": "천"},
        {"hanja": "人", "meaning": "사람", "reading": "인"},
        {"hanja": "十", "meaning": "열", "reading": "십"},
        {"hanja": "因", "meaning": "인하다", "reading": "인"},
        {"hanja": "中", "meaning": "가운데", "reading": "중"},
        {"hanja": "小", "meaning": "작다", "reading": "소"},
        {"hanja": "逢", "meaning": "만나다", "reading": "봉"},
        {"hanja": "尤", "meaning": "더욱", "reading": "우"},
        {"hanja": "八", "meaning": "여덟", "reading": "팔"},
        {"hanja": "入", "meaning": "들어가다", "reading": "입"},
        {"hanja": "犬", "meaning": "개", "reading": "견"},
        {"hanja": "太", "meaning": "크다", "reading": "태"},
        {"hanja": "已", "meaning": "이미", "reading": "이"},
        {"hanja": "巳", "meaning": "여섯째 지지", "reading": "사"},
        {"hanja": "比", "meaning": "견주다", "reading": "비"},
        {"hanja": "例", "meaning": "본보기", "reading": "례"},
        {"hanja": "興", "meaning": "일다", "reading": "흥"},
        {"hanja": "仁", "meaning": "어질다", "reading": "인"},
        {"hanja": "之", "meaning": "가다, 어조사", "reading": "지"},
        {"hanja": "字", "meaning": "글자", "reading": "자"},
        {"hanja": "文", "meaning": "글월", "reading": "문"},
        {"hanja": "學", "meaning": "배우다", "reading": "학"},
        {"hanja": "校", "meaning": "학교", "reading": "교"},
        {"hanja": "自", "meaning": "스스로", "reading": "자"},
        {"hanja": "己", "meaning": "몸, 자기", "reading": "기"},
        {"hanja": "家", "meaning": "집", "reading": "가"},
        {"hanja": "族", "meaning": "겨레", "reading": "족"},
        {"hanja": "世", "meaning": "세상", "reading": "세"},
        {"hanja": "界", "meaning": "지경", "reading": "계"},
        {"hanja": "然", "meaning": "그러하다", "reading": "연"},
        {"hanja": "話", "meaning": "말씀", "reading": "화"},
        {"hanja": "者", "meaning": "사람", "reading": "자"},
        {"hanja": "光", "meaning": "빛", "reading": "광"},
        {"hanja": "合", "meaning": "합하다", "reading": "합"},
        {"hanja": "成", "meaning": "이루다", "reading": "성"},
        {"hanja": "分", "meaning": "나누다", "reading": "분"},
        {"hanja": "子", "meaning": "아들", "reading": "자"},
        {"hanja": "母", "meaning": "어머니", "reading": "모"},
        {"hanja": "形", "meaning": "모양", "reading": "형"},
        {"hanja": "音", "meaning": "소리", "reading": "음"},
        {"hanja": "義", "meaning": "옳다, 뜻", "reading": "의"},
        {"hanja": "魚", "meaning": "물고기", "reading": "어"},
        {"hanja": "天", "meaning": "하늘", "reading": "천"},
        {"hanja": "地", "meaning": "땅", "reading": "지"},
        {"hanja": "貝", "meaning": "조개", "reading": "패"},
        {"hanja": "肉", "meaning": "고기", "reading": "육"},
        {"hanja": "衣", "meaning": "옷", "reading": "의"},
        {"hanja": "廣", "meaning": "넓다", "reading": "광"},
        {"hanja": "圖", "meaning": "그림", "reading": "도"},
        {"hanja": "兩", "meaning": "둘", "reading": "량"},
        {"hanja": "齒", "meaning": "이", "reading": "치"}
    ],
    "2과": [
        {"hanja": "大", "meaning": "크다", "reading": "대"},
        {"hanja": "韓", "meaning": "나라 이름", "reading": "한"},
        {"hanja": "民", "meaning": "백성", "reading": "민"},
        {"hanja": "國", "meaning": "나라", "reading": "국"},
        {"hanja": "順", "meaning": "순하다, 따르다", "reading": "순"},
        {"hanja": "序", "meaning": "차례", "reading": "서"},
        {"hanja": "口", "meaning": "입", "reading": "구"},
        {"hanja": "筆", "meaning": "붓", "reading": "필"},
        {"hanja": "源", "meaning": "근원", "reading": "원"},
        {"hanja": "則", "meaning": "법칙", "reading": "칙"},
        {"hanja": "三", "meaning": "셋", "reading": "삼"},
        {"hanja": "川", "meaning": "내", "reading": "천"},
        {"hanja": "人", "meaning": "사람", "reading": "인"},
        {"hanja": "十", "meaning": "열", "reading": "십"},
        {"hanja": "因", "meaning": "인하다", "reading": "인"},
        {"hanja": "中", "meaning": "가운데", "reading": "중"},
        {"hanja": "小", "meaning": "작다", "reading": "소"},
        {"hanja": "逢", "meaning": "만나다", "reading": "봉"},
        {"hanja": "尤", "meaning": "더욱", "reading": "우"},
        {"hanja": "八", "meaning": "여덟", "reading": "팔"},
        {"hanja": "入", "meaning": "들어가다", "reading": "입"},
        {"hanja": "犬", "meaning": "개", "reading": "견"},
        {"hanja": "太", "meaning": "크다", "reading": "태"},
        {"hanja": "已", "meaning": "이미", "reading": "이"},
        {"hanja": "巳", "meaning": "여섯째 지지", "reading": "사"},
        {"hanja": "比", "meaning": "견주다", "reading": "비"},
        {"hanja": "例", "meaning": "본보기", "reading": "례"},
        {"hanja": "興", "meaning": "일다", "reading": "흥"},
        {"hanja": "仁", "meaning": "어질다", "reading": "인"},
        {"hanja": "之", "meaning": "가다, 어조사", "reading": "지"},
        {"hanja": "門", "meaning": "문", "reading": "문"},
        {"hanja": "崇", "meaning": "높다", "reading": "숭"},
        {"hanja": "禮", "meaning": "예도", "reading": "례"}
    ],
    "3과": [
    {"hanja": "日", "meaning": "해, 날", "reading": "일"},
    {"hanja": "月", "meaning": "달", "reading": "월"},
    {"hanja": "山", "meaning": "산", "reading": "산"},
    {"hanja": "耳", "meaning": "귀", "reading": "이"},
    {"hanja": "目", "meaning": "눈", "reading": "목"},
    {"hanja": "一", "meaning": "하나", "reading": "일"},
    {"hanja": "二", "meaning": "둘", "reading": "이"},
    {"hanja": "上", "meaning": "위", "reading": "상"},
    {"hanja": "下", "meaning": "아래", "reading": "하"},
    {"hanja": "本", "meaning": "뿌리, 근본", "reading": "본"},
    {"hanja": "末", "meaning": "끝", "reading": "말"},
    {"hanja": "火", "meaning": "불", "reading": "화"},
    {"hanja": "水", "meaning": "물", "reading": "수"},
    {"hanja": "木", "meaning": "나무", "reading": "목"},
    {"hanja": "金", "meaning": "쇠", "reading": "금"},
    {"hanja": "土", "meaning": "흙", "reading": "토"},
    {"hanja": "四", "meaning": "넷", "reading": "사"},
    {"hanja": "五", "meaning": "다섯", "reading": "오"},
    {"hanja": "六", "meaning": "여섯", "reading": "륙"},
    {"hanja": "七", "meaning": "일곱", "reading": "칠"},
    {"hanja": "九", "meaning": "아홉", "reading": "구"},
    {"hanja": "父", "meaning": "아버지", "reading": "부"},
    {"hanja": "女", "meaning": "여자", "reading": "녀"},
    {"hanja": "牛", "meaning": "소", "reading": "우"},
    {"hanja": "羊", "meaning": "양", "reading": "양"},
    {"hanja": "馬", "meaning": "말", "reading": "마"},
    {"hanja": "鳥", "meaning": "새", "reading": "조"},
    {"hanja": "位", "meaning": "자리", "reading": "위"},
    {"hanja": "降", "meaning": "내리다", "reading": "강"},
    {"hanja": "根", "meaning": "뿌리", "reading": "근"},
    {"hanja": "端", "meaning": "끝", "reading": "단"}
    ],
    "4과": [
    {"hanja": "休", "meaning": "쉬다", "reading": "휴"},
    {"hanja": "好", "meaning": "좋다", "reading": "호"},
    {"hanja": "林", "meaning": "수풀", "reading": "림"},
    {"hanja": "焰", "meaning": "불꽃", "reading": "염"},
    {"hanja": "江", "meaning": "강", "reading": "강"},
    {"hanja": "河", "meaning": "물", "reading": "하"},
    {"hanja": "海", "meaning": "바다", "reading": "해"},
    {"hanja": "洋", "meaning": "큰 바다", "reading": "양"},
    {"hanja": "工", "meaning": "장인", "reading": "공"},
    {"hanja": "可", "meaning": "옳다", "reading": "가"},
    {"hanja": "毎", "meaning": "매양", "reading": "매"},
    {"hanja": "部", "meaning": "떼", "reading": "부"},
    {"hanja": "首", "meaning": "머리", "reading": "수"},
    {"hanja": "雨", "meaning": "비", "reading": "우"},
    {"hanja": "雲", "meaning": "구름", "reading": "운"},
    {"hanja": "雪", "meaning": "눈", "reading": "설"},
    {"hanja": "霜", "meaning": "서리", "reading": "상"},
    {"hanja": "露", "meaning": "이슬", "reading": "로"},
    {"hanja": "電", "meaning": "번개", "reading": "전"},
    {"hanja": "余", "meaning": "나", "reading": "여"},
    {"hanja": "打", "meaning": "치다", "reading": "벌"},
    {"hanja": "刀", "meaning": "칼", "reading": "도"},
    {"hanja": "初", "meaning": "처음", "reading": "초"},
    {"hanja": "判", "meaning": "판단하다", "reading": "판"},
    {"hanja": "心", "meaning": "마음", "reading": "심"},
    {"hanja": "忍", "meaning": "참다", "reading": "인"},
    {"hanja": "悟", "meaning": "깨닫다", "reading": "오"},
    {"hanja": "氷", "meaning": "얼음", "reading": "빙"},
    {"hanja": "泣", "meaning": "울다", "reading": "읍"},
    {"hanja": "手", "meaning": "손", "reading": "수"},
    {"hanja": "拜", "meaning": "절", "reading": "배"},
    {"hanja": "抱", "meaning": "안다", "reading": "포"}
],
"5과": [
    {"hanja": "身", "meaning": "몸", "reading": "신"},
    {"hanja": "體", "meaning": "몸", "reading": "체"},
    {"hanja": "家", "meaning": "집", "reading": "우"},
    {"hanja": "主", "meaning": "집", "reading": "주"},
    {"hanja": "有", "meaning": "있다", "reading": "유"},
    {"hanja": "無", "meaning": "없다", "reading": "무"},
    {"hanja": "去", "meaning": "가다", "reading": "거"},
    {"hanja": "來", "meaning": "오다", "reading": "래"},
    {"hanja": "淸", "meaning": "맑다", "reading": "청"},
    {"hanja": "風", "meaning": "바람", "reading": "풍"},
    {"hanja": "明", "meaning": "밝다", "reading": "명"},
    {"hanja": "靑", "meaning": "푸르다", "reading": "청"},
    {"hanja": "流", "meaning": "흐르다", "reading": "류"},
    {"hanja": "星", "meaning": "별", "reading": "성"},
    {"hanja": "百", "meaning": "일백", "reading": "백"},
    {"hanja": "花", "meaning": "꽃", "reading": "화"},
    {"hanja": "男", "meaning": "남자", "reading": "남"},
    {"hanja": "老", "meaning": "늙다", "reading": "로"},
    {"hanja": "少", "meaning": "적다, 젊다", "reading": "소"},
    {"hanja": "兄", "meaning": "형", "reading": "형"},
    {"hanja": "弟", "meaning": "아우", "reading": "제"},
    {"hanja": "姉", "meaning": "손위 누이", "reading": "자"},
    {"hanja": "妹", "meaning": "손 아래 누이", "reading": "매"},
    {"hanja": "草", "meaning": "풀", "reading": "초"},
    {"hanja": "辰 지지", "meaning": "다섯째 지지", "reading": "진"},
    {"hanja": "辰 별", "meaning": "별", "reading": "신"},
    {"hanja": "是", "meaning": "옳다", "reading": "시"},
    {"hanja": "非", "meaning": "아니다", "reading": "비"},
    {"hanja": "天", "meaning": "하늘", "reading": "건"},
    {"hanja": "地", "meaning": "땅", "reading": "곤"},
    {"hanja": "公", "meaning": "공평하다", "reading": "공"},
    {"hanja": "私", "meaning": "사사롭다", "reading": "사"},
    {"hanja": "永", "meaning": "길다", "reading": "영"},
    {"hanja": "久", "meaning": "오래다", "reading": "구"},
    {"hanja": "皇", "meaning": "임금", "reading": "황"},
    {"hanja": "帝", "meaning": "임금", "reading": "제"},
    {"hanja": "必", "meaning": "반드시", "reading": "필"},
    {"hanja": "須", "meaning": "모름지기, 반드시", "reading": "수"}
],
"6과": [
    {"hanja": "出", "meaning": "나가다", "reading": "출"},
    {"hanja": "年", "meaning": "해", "reading": "년"},
    {"hanja": "和", "meaning": "화목하다", "reading": "화"},
    {"hanja": "讀", "meaning": "읽다", "reading": "독"},
    {"hanja": "書", "meaning": "글, 책", "reading": "서"},
    {"hanja": "修", "meaning": "닦다", "reading": "수"},
    {"hanja": "愛", "meaning": "사랑하다", "reading": "애"},
    {"hanja": "登", "meaning": "오르다", "reading": "등"},
    {"hanja": "多", "meaning": "많다", "reading": "다"},
    {"hanja": "正", "meaning": "뜻", "reading": "정"},
    {"hanja": "東", "meaning": "동쪽", "reading": "동"},
    {"hanja": "西", "meaning": "서쪽", "reading": "서"},
    {"hanja": "南", "meaning": "남쪽", "reading": "남"},
    {"hanja": "北", "meaning": "북쪽", "reading": "북"},
    {"hanja": "前", "meaning": "앞", "reading": "전"},
    {"hanja": "後", "meaning": "뒤", "reading": "후"},
    {"hanja": "左", "meaning": "왼쪽", "reading": "좌"},
    {"hanja": "右", "meaning": "오른쪽", "reading": "우"},
    {"hanja": "高", "meaning": "높다", "reading": "고"},
    {"hanja": "低", "meaning": "낮다", "reading": "저"},
    {"hanja": "長", "meaning": "길다", "reading": "장"},
    {"hanja": "短", "meaning": "짧다", "reading": "단"},
    {"hanja": "强", "meaning": "강하다", "reading": "강"},
    {"hanja": "弱", "meaning": "약하다", "reading": "약"},
    {"hanja": "輕", "meaning": "가볍다", "reading": "경"},
    {"hanja": "重", "meaning": "무겁다", "reading": "중"},
    {"hanja": "千", "meaning": "일천", "reading": "천"},
    {"hanja": "萬", "meaning": "일만", "reading": "만"},
    {"hanja": "億", "meaning": "억", "reading": "억"},
    {"hanja": "兆", "meaning": "조", "reading": "조"},
    {"hanja": "席", "meaning": "자리", "reading": "석"},
    {"hanja": "試", "meaning": "시험하다", "reading": "시"},
    {"hanja": "歲", "meaning": "해", "reading": "세"},
    {"hanja": "昨", "meaning": "어제", "reading": "작"}
],
"7과": [
    {"hanja": "竹", "meaning": "대나무", "reading": "죽"},
    {"hanja": "故", "meaning": "연고, 예", "reading": "고"},
    {"hanja": "友", "meaning": "벗", "reading": "우"},
    {"hanja": "莫", "meaning": "없다", "reading": "막"},
    {"hanja": "逆", "meaning": "거스르다", "reading": "역"},
    {"hanja": "知", "meaning": "알다", "reading": "지"},
    {"hanja": "交", "meaning": "사귀다", "reading": "교"},
    {"hanja": "石", "meaning": "돌", "reading": "석"},
    {"hanja": "岩", "meaning": "바위", "reading": "암"},
    {"hanja": "化", "meaning": "되다", "reading": "화"},
    {"hanja": "製", "meaning": "짓다", "reading": "제"},
    {"hanja": "田", "meaning": "밭", "reading": "전"},
    {"hanja": "耕", "meaning": "밭 갈다", "reading": "경"},
    {"hanja": "油", "meaning": "기름", "reading": "유"},
    {"hanja": "原", "meaning": "동산", "reading": "원"},
    {"hanja": "稅", "meaning": "세금", "reading": "세"},
    {"hanja": "戶", "meaning": "집", "reading": "호"},
    {"hanja": "關", "meaning": "관계하다", "reading": "관"},
    {"hanja": "內", "meaning": "안", "reading": "내"},
    {"hanja": "性", "meaning": "성", "reading": "성"},
    {"hanja": "車 수레", "meaning": "수레", "reading": "거"},
    {"hanja": "車 차", "meaning": "차", "reading": "차"},
    {"hanja": "窗", "meaning": "창문", "reading": "창"},
    {"hanja": "客", "meaning": "손님", "reading": "객"},
    {"hanja": "乘", "meaning": "타다", "reading": "승"},
    {"hanja": "列", "meaning": "벌이다", "reading": "렬"},
    {"hanja": "飮", "meaning": "마시다", "reading": "음"},
    {"hanja": "淨", "meaning": "깨끗하다", "reading": "정"},
    {"hanja": "香", "meaning": "향기", "reading": "향"},
    {"hanja": "銀", "meaning": "은", "reading": "은"},
    {"hanja": "質", "meaning": "바탕", "reading": "질"},
    {"hanja": "易", "meaning": "바꾸다", "reading": "역"},
    {"hanja": "遊", "meaning": "놀다", "reading": "유"},
    {"hanja": "外", "meaning": "바깥", "reading": "외"},
    {"hanja": "絶", "meaning": "끊다", "reading": "절"},
    {"hanja": "朋", "meaning": "벗", "reading": "붕"},
    {"hanja": "信", "meaning": "믿다", "reading": "신"},
    {"hanja": "親", "meaning": "친하다", "reading": "친"},
    {"hanja": "舊", "meaning": "예", "reading": "구"}
],
"8과": [
    {"hanja": "言", "meaning": "말씀", "reading": "언"},
    {"hanja": "骨", "meaning": "뼈", "reading": "고"},
    {"hanja": "忠", "meaning": "충성", "reading": "충"},
    {"hanja": "頂", "meaning": "정수리", "reading": "정"},
    {"hanja": "針", "meaning": "바늘", "reading": "침"},
    {"hanja": "寸", "meaning": "마디", "reading": "촌"},
    {"hanja": "鐵", "meaning": "쇠", "reading": "철"},
    {"hanja": "殺", "meaning": "죽이다", "reading": "살"},
    {"hanja": "行", "meaning": "다니다", "reading": "행"},
    {"hanja": "致", "meaning": "이르다", "reading": "치"},
    {"hanja": "衆", "meaning": "무리", "reading": "중"},
    {"hanja": "約", "meaning": "맺다", "reading": "약"},
    {"hanja": "論", "meaning": "논하다", "reading": "론"},
    {"hanja": "遺", "meaning": "남기다", "reading": "유"},
    {"hanja": "語", "meaning": "말씀", "reading": "어"},
    {"hanja": "句", "meaning": "글귀", "reading": "구"},
    {"hanja": "調", "meaning": "고르다", "reading": "조"},
    {"hanja": "單", "meaning": "홑", "reading": "단"},
    {"hanja": "用", "meaning": "쓰다", "reading": "용"},
    {"hanja": "對", "meaning": "대하다", "reading": "대"},
    {"hanja": "通", "meaning": "통하다", "reading": "통"},
    {"hanja": "頭", "meaning": "머리", "reading": "두"},
    {"hanja": "題", "meaning": "제목", "reading": "제"},
    {"hanja": "實", "meaning": "실", "reading": "사"},
    {"hanja": "路", "meaning": "길", "reading": "로"},
    {"hanja": "橋", "meaning": "다리", "reading": "교"},
    {"hanja": "純", "meaning": "순수하다", "reading": "순"},
    {"hanja": "巨", "meaning": "크다", "reading": "거"},
    {"hanja": "偉", "meaning": "크다", "reading": "위"},
    {"hanja": "全", "meaning": "온전", "reading": "전"},
    {"hanja": "證", "meaning": "증거", "reading": "증"},
    {"hanja": "個", "meaning": "낱", "reading": "개"},
    {"hanja": "表", "meaning": "겉", "reading": "표"},
    {"hanja": "現", "meaning": "나타나다", "reading": "현"},
    {"hanja": "生", "meaning": "나다", "reading": "생"},
    {"hanja": "活", "meaning": "살다", "reading": "활"},
    {"hanja": "注", "meaning": "물 대다", "reading": "주"},
    {"hanja": "義", "meaning": "뜻", "reading": "의"}
],
"9과": [
    {"hanja": "漁", "meaning": "고기 잡다", "reading": "어"},
    {"hanja": "利", "meaning": "이롭다", "reading": "리"},
    {"hanja": "結", "meaning": "맺다", "reading": "결"},
    {"hanja": "報", "meaning": "알리다, 갚다", "reading": "보"},
    {"hanja": "恩", "meaning": "은혜", "reading": "은"},
    {"hanja": "益", "meaning": "더하다", "reading": "익"},
    {"hanja": "善", "meaning": "착하다", "reading": "선"},
    {"hanja": "面", "meaning": "얼굴", "reading": "면"},
    {"hanja": "楚", "meaning": "초나라", "reading": "초"},
    {"hanja": "歌", "meaning": "노래", "reading": "가"},
    {"hanja": "顔", "meaning": "얼굴", "reading": "안"},
    {"hanja": "紙", "meaning": "종이", "reading": "지"},
    {"hanja": "方", "meaning": "모, 방위", "reading": "방"},
    {"hanja": "惡", "meaning": "악하다", "reading": "악"},
    {"hanja": "次", "meaning": "버금", "reading": "차"},
    {"hanja": "防", "meaning": "막다", "reading": "방"},
    {"hanja": "害", "meaning": "해치다", "reading": "해"},
    {"hanja": "他", "meaning": "다르다, 남", "reading": "타"},
    {"hanja": "便", "meaning": "편하다", "reading": "편"},
    {"hanja": "權", "meaning": "권세", "reading": "권"},
    {"hanja": "果", "meaning": "열매", "reading": "과"},
    {"hanja": "終", "meaning": "마치다", "reading": "종"},
    {"hanja": "連", "meaning": "잇다", "reading": "련"},
    {"hanja": "直", "meaning": "곧다", "reading": "직"},
    {"hanja": "才", "meaning": "재주", "reading": "재"},
    {"hanja": "幸", "meaning": "다행", "reading": "행"},
    {"hanja": "量", "meaning": "헤아리다", "reading": "량"},
    {"hanja": "種", "meaning": "씨, 종류", "reading": "종"},
    {"hanja": "難", "meaning": "어렵다", "reading": "난"},
    {"hanja": "舞", "meaning": "춤추다", "reading": "무"},
    {"hanja": "軍", "meaning": "군사", "reading": "군"},
    {"hanja": "曲", "meaning": "굽다, 노래", "reading": "곡"},
    {"hanja": "祝", "meaning": "빌다", "reading": "축"},
    {"hanja": "歷", "meaning": "지내다", "reading": "력"},
    {"hanja": "史", "meaning": "역사", "reading": "사"},
    {"hanja": "由", "meaning": "말미암다", "reading": "유"},
    {"hanja": "事", "meaning": "일", "reading": "사"}
],
"10과": [
    {"hanja": "含", "meaning": "다", "reading": "함"},
    {"hanja": "差", "meaning": "다르다, 사신 보내다", "reading": "차"},
    {"hanja": "使", "meaning": "부리다", "reading": "사"},
    {"hanja": "鷄", "meaning": "닭", "reading": "계"},
    {"hanja": "卵", "meaning": "알", "reading": "란"},
    {"hanja": "朝", "meaning": "아침", "reading": "조"},
    {"hanja": "暮", "meaning": "저물다", "reading": "모"},
    {"hanja": "狐", "meaning": "여우", "reading": "호"},
    {"hanja": "假", "meaning": "거짓", "reading": "가"},
    {"hanja": "虎", "meaning": "범", "reading": "호"},
    {"hanja": "威", "meaning": "위엄", "reading": "엄"},
    {"hanja": "亡", "meaning": "망하다", "reading": "망"},
    {"hanja": "復 회복", "meaning": "회복하다", "reading": "복"},
    {"hanja": "復 다시", "meaning": "다시", "reading": "부"},
    {"hanja": "敗", "meaning": "패하다", "reading": "패"},
    {"hanja": "夕", "meaning": "저녁", "reading": "석"},
    {"hanja": "早", "meaning": "이르다", "reading": "조"},
    {"hanja": "陽", "meaning": "볕", "reading": "양"},
    {"hanja": "眞", "meaning": "참", "reading": "진"},
    {"hanja": "實", "meaning": "열매", "reading": "실"},
    {"hanja": "定", "meaning": "정하다", "reading": "정"},
    {"hanja": "先", "meaning": "먼저", "reading": "선"},
    {"hanja": "祖", "meaning": "할아버지", "reading": "조"},
    {"hanja": "孫", "meaning": "손자", "reading": "손"},
    {"hanja": "能", "meaning": "능하다", "reading": "능"},
    {"hanja": "識", "meaning": "알다", "reading": "식"},
    {"hanja": "共", "meaning": "함께", "reading": "공"},
    {"hanja": "罪", "meaning": "허물", "reading": "죄"},
    {"hanja": "力", "meaning": "힘", "reading": "력"},
    {"hanja": "引", "meaning": "끌다", "reading": "인"},
    {"hanja": "勢", "meaning": "형세", "reading": "세"},
    {"hanja": "協", "meaning": "돕다", "reading": "협"},
    {"hanja": "持", "meaning": "가지다", "reading": "지"},
    {"hanja": "效", "meaning": "본받다", "reading": "효"},
    {"hanja": "都", "meaning": "도읍", "reading": "도"},
    {"hanja": "邑", "meaning": "고을", "reading": "읍"},
    {"hanja": "宗", "meaning": "마루", "reading": "종"},
    {"hanja": "臣", "meaning": "신하", "reading": "신"},
    {"hanja": "領", "meaning": "거느리다", "reading": "령"},
    {"hanja": "議", "meaning": "의논", "reading": "의"},
    {"hanja": "政", "meaning": "정사", "reading": "정"}
],
"11과": [
    {"hanja": "五", "meaning": "나", "reading": "오"},
    {"hanja": "鼻", "meaning": "코", "reading": "비"},
    {"hanja": "尺", "meaning": "자", "reading": "척"},
    {"hanja": "座", "meaning": "앉다", "reading": "좌"},
    {"hanja": "井", "meaning": "우물", "reading": "정"},
    {"hanja": "觀", "meaning": "보다", "reading": "관"},
    {"hanja": "習", "meaning": "익히다", "reading": "습"},
    {"hanja": "至", "meaning": "이르다", "reading": "지"},
    {"hanja": "語", "meaning": "어조사", "reading": "우"},
    {"hanja": "里", "meaning": "마을, 거리 단위", "reading": "리"},
    {"hanja": "始", "meaning": "비로소", "reading": "시"},
    {"hanja": "語", "meaning": "어조사", "reading": "어"},
    {"hanja": "足", "meaning": "발", "reading": "족"},
    {"hanja": "旅", "meaning": "나그네", "reading": "려"},
    {"hanja": "尾", "meaning": "꼬리", "reading": "미"},
    {"hanja": "立", "meaning": "서다", "reading": "립"},
    {"hanja": "獨", "meaning": "홀로", "reading": "독"},
    {"hanja": "脚", "meaning": "다리", "reading": "각"},
    {"hanja": "步", "meaning": "걸음", "reading": "보"},
    {"hanja": "徒", "meaning": "무리", "reading": "도"},
    {"hanja": "讓", "meaning": "사양하다", "reading": "양"},
    {"hanja": "走", "meaning": "달리다", "reading": "주"},
    {"hanja": "完", "meaning": "완전하다", "reading": "완"},
    {"hanja": "暴", "meaning": "사납다", "reading": "폭"},
    {"hanja": "燈", "meaning": "등불", "reading": "등"},
    {"hanja": "不", "meaning": "아니다", "reading": "불"},
    {"hanja": "烏", "meaning": "까마귀", "reading": "오"},
    {"hanja": "飛", "meaning": "날다", "reading": "비"},
    {"hanja": "梨", "meaning": "배나무", "reading": "리"},
    {"hanja": "落", "meaning": "떨어지다", "reading": "락"},
    {"hanja": "苦", "meaning": "쓰다", "reading": "고"},
    {"hanja": "盡", "meaning": "다하다", "reading": "진"},
    {"hanja": "甘", "meaning": "달다", "reading": "감"},
    {"hanja": "俗", "meaning": "풍속", "reading": "속"},
    {"hanja": "談", "meaning": "말씀", "reading": "담"},
    {"hanja": "間", "meaning": "사이", "reading": "간"},
    {"hanja": "傳", "meaning": "전하다", "reading": "전"},
    {"hanja": "承", "meaning": "잇다", "reading": "승"},
    {"hanja": "敎", "meaning": "가르치다", "reading": "교"},
    {"hanja": "訓", "meaning": "가르치다", "reading": "훈"}
],
"12과": [
    {"hanja": "器", "meaning": "그릇", "reading": "기"},
    {"hanja": "晚", "meaning": "늦다", "reading": "만"},
    {"hanja": "敵", "meaning": "대적하다", "reading": "적"},
    {"hanja": "如", "meaning": "같다", "reading": "여"},
    {"hanja": "樂", "meaning": "즐겁다", "reading": "락"},
    {"hanja": "精", "meaning": "자세하다", "reading": "정"},
    {"hanja": "神", "meaning": "귀신", "reading": "신"},
    {"hanja": "道", "meaning": "이르다", "reading": "도"},
    {"hanja": "何", "meaning": "어찌", "reading": "하"},
    {"hanja": "增", "meaning": "더하다", "reading": "증"},
    {"hanja": "豆", "meaning": "콩", "reading": "두"},
    {"hanja": "麥", "meaning": "보리", "reading": "맥"},
    {"hanja": "限", "meaning": "한정하다", "reading": "한"},
    {"hanja": "價", "meaning": "값", "reading": "가"},
    {"hanja": "虛", "meaning": "비다", "reading": "허"},
    {"hanja": "料", "meaning": "헤아리다", "reading": "료"},
    {"hanja": "慶", "meaning": "경사", "reading": "경"},
    {"hanja": "凡", "meaning": "무릇", "reading": "범"},
    {"hanja": "從", "meaning": "따르다", "reading": "종"},
    {"hanja": "執", "meaning": "잡다", "reading": "집"},
    {"hanja": "刑", "meaning": "형벌", "reading": "형"},
    {"hanja": "務", "meaning": "힘쓰다", "reading": "무"},
    {"hanja": "性", "meaning": "성품", "reading": "성"},
    {"hanja": "品", "meaning": "물건", "reading": "품"},
    {"hanja": "倫", "meaning": "인륜", "reading": "륜"},
    {"hanja": "聖", "meaning": "성인", "reading": "성"},
    {"hanja": "佳", "meaning": "아름답다", "reading": "가"},
    {"hanja": "仙", "meaning": "신선", "reading": "선"},
    {"hanja": "發", "meaning": "피다", "reading": "발"},
    {"hanja": "憤", "meaning": "분하다", "reading": "분"},
    {"hanja": "忘", "meaning": "잊다", "reading": "망"},
    {"hanja": "食", "meaning": "먹다", "reading": "식"},
    {"hanja": "趣", "meaning": "나아가다", "reading": "취"},
    {"hanja": "將", "meaning": "장수, 나아가다", "reading": "장"},
    {"hanja": "晝", "meaning": "낮", "reading": "주"},
    {"hanja": "夜", "meaning": "밤", "reading": "야"},
    {"hanja": "泰", "meaning": "크다", "reading": "태"},
    {"hanja": "斗", "meaning": "말", "reading": "두"}
],
"13과": [
    {"hanja": "盾", "meaning": "방패, 천간", "reading": "간"},
    {"hanja": "甲", "meaning": "갑옷, 첫째 천간", "reading": "갑"},
    {"hanja": "乙", "meaning": "둘째 천간", "reading": "을"},
    {"hanja": "丙", "meaning": "셋째 천간", "reading": "병"},
    {"hanja": "丁", "meaning": "장정, 넷째 천간", "reading": "정"},
    {"hanja": "戊", "meaning": "다섯째 천간", "reading": "무"},
    {"hanja": "庚", "meaning": "일곱째 천간", "reading": "경"},
    {"hanja": "辛", "meaning": "맵다, 여덟째 천간", "reading": "신"},
    {"hanja": "壬", "meaning": "아홉째 천간", "reading": "임"},
    {"hanja": "癸", "meaning": "열째 천간", "reading": "계"},
    {"hanja": "支", "meaning": "지탱하다, 지지", "reading": "지"},
    {"hanja": "丑", "meaning": "둘째 지지", "reading": "축"},
    {"hanja": "寅", "meaning": "셋째 지지", "reading": "인"},
    {"hanja": "卯", "meaning": "넷째 지지", "reading": "묘"},
    {"hanja": "午", "meaning": "낮, 일곱째 지지", "reading": "오"},
    {"hanja": "未", "meaning": "아니다, 여덟째 지지", "reading": "미"},
    {"hanja": "申", "meaning": "아홉째 지지", "reading": "신"},
    {"hanja": "酉", "meaning": "열째 지지", "reading": "유"},
    {"hanja": "戌", "meaning": "열한째 지지", "reading": "술"},
    {"hanja": "亥", "meaning": "열둘째 지지", "reading": "해"},
    {"hanja": "乃", "meaning": "이에", "reading": "내"},
    {"hanja": "李", "meaning": "자두나무", "reading": "리"},
    {"hanja": "秀", "meaning": "빼어나다", "reading": "수"},
    {"hanja": "早", "meaning": "일찍", "reading": "증"},
    {"hanja": "會", "meaning": "모이다", "reading": "회"},
    {"hanja": "誰", "meaning": "누구", "reading": "수"},
    {"hanja": "雖", "meaning": "비록", "reading": "수"},
    {"hanja": "季", "meaning": "계절", "reading": "계"},
    {"hanja": "節", "meaning": "마디", "reading": "절"},
    {"hanja": "春", "meaning": "봄", "reading": "춘"},
    {"hanja": "夏", "meaning": "여름", "reading": "하"},
    {"hanja": "秋", "meaning": "가을", "reading": "추"},
    {"hanja": "冬", "meaning": "겨울", "reading": "동"},
    {"hanja": "暖", "meaning": "따뜻하다", "reading": "난"},
    {"hanja": "暑", "meaning": "덥다", "reading": "서"},
    {"hanja": "涼", "meaning": "서늘하다", "reading": "량"},
    {"hanja": "寒", "meaning": "차다", "reading": "한"},
    {"hanja": "波", "meaning": "물결", "reading": "파"},
    {"hanja": "回", "meaning": "돌다", "reading": "회"},
    {"hanja": "同", "meaning": "한가지", "reading": "동"}
],
"14과": [
    {"hanja": "古", "meaning": "예", "reading": "고"},
    {"hanja": "以", "meaning": "써", "reading": "이"},
    {"hanja": "名", "meaning": "이름", "reading": "호"},
    {"hanja": "代", "meaning": "대신하다", "reading": "대"},
    {"hanja": "名", "meaning": "이름", "reading": "명"},
    {"hanja": "矣", "meaning": "어조사", "reading": "의"},
    {"hanja": "別", "meaning": "다르다", "reading": "별"},
    {"hanja": "或", "meaning": "혹시", "reading": "혹"},
    {"hanja": "師", "meaning": "스승", "reading": "사"},
    {"hanja": "所", "meaning": "바", "reading": "소"},
    {"hanja": "也", "meaning": "어조사", "reading": "야"},
    {"hanja": "色", "meaning": "빛", "reading": "색"},
    {"hanja": "黃", "meaning": "누렇다", "reading": "황"},
    {"hanja": "白", "meaning": "희다", "reading": "백"},
    {"hanja": "赤", "meaning": "붉다", "reading": "적"},
    {"hanja": "黑", "meaning": "검다", "reading": "흑"},
    {"hanja": "朱", "meaning": "붉다", "reading": "주"},
    {"hanja": "丹", "meaning": "붉다", "reading": "단"},
    {"hanja": "紅", "meaning": "붉다", "reading": "홍"},
    {"hanja": "綠", "meaning": "푸르다", "reading": "록"},
    {"hanja": "姓", "meaning": "성씨", "reading": "성"},
    {"hanja": "作", "meaning": "짓다", "reading": "작"},
    {"hanja": "藝", "meaning": "재주", "reading": "예"},
    {"hanja": "借", "meaning": "빌리다", "reading": "차"},
    {"hanja": "議", "meaning": "의원", "reading": "의"},
    {"hanja": "氏", "meaning": "성씨", "reading": "씨"},
    {"hanja": "美", "meaning": "아름답다", "reading": "미"},
    {"hanja": "良", "meaning": "어질다", "reading": "량"},
    {"hanja": "冠", "meaning": "갓", "reading": "관"},
    {"hanja": "婚", "meaning": "혼인하다", "reading": "혼"},
    {"hanja": "喪", "meaning": "잃다", "reading": "상"},
    {"hanja": "祭", "meaning": "제사", "reading": "제"},
    {"hanja": "伯", "meaning": "맏", "reading": "백"},
    {"hanja": "仲", "meaning": "버금", "reading": "중"},
    {"hanja": "叔", "meaning": "아저씨", "reading": "숙"},
    {"hanja": "吉", "meaning": "길하다", "reading": "길"},
    {"hanja": "凶", "meaning": "흉하다", "reading": "흉"},
    {"hanja": "禍", "meaning": "재앙", "reading": "화"},
    {"hanja": "福", "meaning": "복", "reading": "복"}
],
"15과": [
    {"hanja": "武", "meaning": "무사", "reading": "무"},
    {"hanja": "陵", "meaning": "언덕", "reading": "릉"},
    {"hanja": "島", "meaning": "섬", "reading": "도"},
    {"hanja": "在", "meaning": "있다", "reading": "재"},
    {"hanja": "縣", "meaning": "고을", "reading": "현"},
    {"hanja": "正", "meaning": "바르다", "reading": "정"},
    {"hanja": "相", "meaning": "서로", "reading": "상"},
    {"hanja": "遠", "meaning": "멀다", "reading": "원"},
    {"hanja": "望", "meaning": "바라다", "reading": "망"},
    {"hanja": "見", "meaning": "보다", "reading": "견"},
    {"hanja": "聞", "meaning": "듣다", "reading": "문"},
    {"hanja": "異", "meaning": "다르다", "reading": "이"},
    {"hanja": "念", "meaning": "생각", "reading": "념"},
    {"hanja": "參", "meaning": "참여하다", "reading": "참"},
    {"hanja": "看", "meaning": "보다", "reading": "간"},
    {"hanja": "病", "meaning": "병", "reading": "병"},
    {"hanja": "破", "meaning": "깨뜨리다", "reading": "파"},
    {"hanja": "視", "meaning": "보다", "reading": "시"},
    {"hanja": "聽", "meaning": "듣다", "reading": "청"},
    {"hanja": "角", "meaning": "뿔", "reading": "각"},
    {"hanja": "示", "meaning": "보이다", "reading": "시"},
    {"hanja": "指", "meaning": "가리키다", "reading": "지"},
    {"hanja": "暗", "meaning": "어둡다", "reading": "암"},
    {"hanja": "希", "meaning": "바라다", "reading": "희"},
    {"hanja": "熱", "meaning": "덥다", "reading": "열"},
    {"hanja": "渴", "meaning": "목마르다", "reading": "갈"},
    {"hanja": "展", "meaning": "펴다", "reading": "전"},
    {"hanja": "血", "meaning": "피", "reading": "혈"},
    {"hanja": "眼", "meaning": "눈", "reading": "안"},
    {"hanja": "胸", "meaning": "가슴", "reading": "흉"},
    {"hanja": "的", "meaning": "과녁", "reading": "적"},
    {"hanja": "陸", "meaning": "뭍", "reading": "륙"},
    {"hanja": "平", "meaning": "평평하다", "reading": "평"},
    {"hanja": "野", "meaning": "들", "reading": "야"},
    {"hanja": "溪", "meaning": "시내", "reading": "계"},
    {"hanja": "谷", "meaning": "골", "reading": "곡"},
    {"hanja": "湖", "meaning": "호수", "reading": "호"},
    {"hanja": "溫", "meaning": "따뜻하다", "reading": "온"},
    {"hanja": "泉", "meaning": "샘", "reading": "천"}
],
"16과": [
    {"hanja": "省", "meaning": "살피다", "reading": "성"},
    {"hanja": "欲", "meaning": "하고자 하다", "reading": "욕"},
    {"hanja": "勿", "meaning": "말다", "reading": "물"},
    {"hanja": "施", "meaning": "베풀다", "reading": "시"},
    {"hanja": "得", "meaning": "얻다", "reading": "득"},
    {"hanja": "皆", "meaning": "모두", "reading": "개"},
    {"hanja": "反", "meaning": "돌이키다", "reading": "반"},
    {"hanja": "求", "meaning": "구하다", "reading": "구"},
    {"hanja": "諸 모두", "meaning": "모두", "reading": "제"},
    {"hanja": "諸 어조사", "meaning": "어조사", "reading": "저"},
    {"hanja": "苟", "meaning": "진실로", "reading": "구"},
    {"hanja": "新", "meaning": "새", "reading": "신"},
    {"hanja": "又", "meaning": "또", "reading": "우"},
    {"hanja": "察", "meaning": "살피다", "reading": "찰"},
    {"hanja": "洞 고을", "meaning": "고을", "reading": "동"},
    {"hanja": "洞 꿰뚫다", "meaning": "꿰뚫다", "reading": "통"},
    {"hanja": "動", "meaning": "움직이다", "reading": "동"},
    {"hanja": "敢", "meaning": "감히", "reading": "감"},
    {"hanja": "受", "meaning": "받다", "reading": "수"},
    {"hanja": "拾", "meaning": "줍다", "reading": "습"},
    {"hanja": "收", "meaning": "거두다", "reading": "수"},
    {"hanja": "過", "meaning": "지나다, 잘못", "reading": "과"},
    {"hanja": "誤", "meaning": "그르치다", "reading": "오"},
    {"hanja": "失", "meaning": "잃다", "reading": "실"},
    {"hanja": "認", "meaning": "알다", "reading": "인"},
    {"hanja": "潔", "meaning": "깨끗하다", "reading": "결"},
    {"hanja": "快", "meaning": "상쾌하다", "reading": "쾌"},
    {"hanja": "毛", "meaning": "털", "reading": "모"},
    {"hanja": "適", "meaning": "맞다", "reading": "적"},
    {"hanja": "應", "meaning": "응하다", "reading": "응"},
    {"hanja": "記", "meaning": "기록하다", "reading": "기"},
    {"hanja": "著", "meaning": "나타나다, 짓다", "reading": "저"},
    {"hanja": "打", "meaning": "치다", "reading": "타"},
    {"hanja": "賢", "meaning": "어질다", "reading": "현"},
    {"hanja": "速", "meaning": "빠르다", "reading": "속"},
    {"hanja": "達", "meaning": "통달하다", "reading": "달"},
    {"hanja": "思", "meaning": "생각", "reading": "사"},
    {"hanja": "推", "meaning": "밀다", "reading": "추"},
    {"hanja": "及", "meaning": "미치다", "reading": "급"}
],
"17과": [
    {"hanja": "我", "meaning": "나", "reading": "아"},
    {"hanja": "飼", "meaning": "기르다", "reading": "국"},
    {"hanja": "告 알리다", "meaning": "알리다", "reading": "고"},
    {"hanja": "告 아뢰다", "meaning": "아뢰다", "reading": "곡"},
    {"hanja": "樹", "meaning": "나무", "reading": "수"},
    {"hanja": "靜", "meaning": "고요하다", "reading": "정"},
    {"hanja": "續", "meaning": "말 잇다", "reading": "이"},
    {"hanja": "止", "meaning": "그치다", "reading": "지"},
    {"hanja": "養", "meaning": "기르다", "reading": "양"},
    {"hanja": "待", "meaning": "기다리다", "reading": "대"},
    {"hanja": "産", "meaning": "낳다", "reading": "산"},
    {"hanja": "育", "meaning": "기르다", "reading": "육"},
    {"hanja": "存", "meaning": "있다", "reading": "존"},
    {"hanja": "厚", "meaning": "두텁다", "reading": "후"},
    {"hanja": "近", "meaning": "가깝다", "reading": "근"},
    {"hanja": "密", "meaning": "빽빽하다", "reading": "밀"},
    {"hanja": "愛", "meaning": "사랑하다", "reading": "자"},
    {"hanja": "嚴", "meaning": "엄하다", "reading": "엄"},
    {"hanja": "屋", "meaning": "집", "reading": "옥"},
    {"hanja": "妻", "meaning": "아내", "reading": "처"},
    {"hanja": "畫", "meaning": "그림", "reading": "화"},
    {"hanja": "勸", "meaning": "권하다", "reading": "권"},
    {"hanja": "進", "meaning": "나아가다", "reading": "진"},
    {"hanja": "選", "meaning": "가리다", "reading": "선"},
    {"hanja": "各", "meaning": "각각", "reading": "각"},
    {"hanja": "放", "meaning": "놓다", "reading": "방"},
    {"hanja": "細", "meaning": "가늘다", "reading": "세"},
    {"hanja": "勞", "meaning": "힘쓰다", "reading": "로"},
    {"hanja": "誠", "meaning": "정성", "reading": "성"},
    {"hanja": "決", "meaning": "결정하다", "reading": "결"},
    {"hanja": "變", "meaning": "변하다", "reading": "변"},
    {"hanja": "孝", "meaning": "효도", "reading": "효"},
    {"hanja": "道", "meaning": "길,도리", "reading": "도"},
    {"hanja": "統", "meaning": "거느리다", "reading": "통"},
    {"hanja": "尊", "meaning": "높다", "reading": "존"},
    {"hanja": "敬", "meaning": "공경", "reading": "경"},
    {"hanja": "感", "meaning": "느끼다", "reading": "감"},
    {"hanja": "謝", "meaning": "사례하다", "reading": "사"},
    {"hanja": "要", "meaning": "중요하다", "reading": "요"}
],
"18과": [
    {"hanja": "危", "meaning": "위태롭다", "reading": "위"},
    {"hanja": "授", "meaning": "주다", "reading": "수"},
    {"hanja": "命", "meaning": "목숨", "reading": "명"},
    {"hanja": "爲", "meaning": "하다", "reading": "위"},
    {"hanja": "勇", "meaning": "날래다", "reading": "용"},
    {"hanja": "死", "meaning": "죽다", "reading": "사"},
    {"hanja": "夫", "meaning": "사나이", "reading": "부"},
    {"hanja": "當", "meaning": "마땅하다", "reading": "당"},
    {"hanja": "徑", "meaning": "좁은 길", "reading": "경"},
    {"hanja": "懼", "meaning": "두려워하다", "reading": "구"},
    {"hanja": "壽", "meaning": "목숨", "reading": "수"},
    {"hanja": "救", "meaning": "구원하다", "reading": "구"},
    {"hanja": "令", "meaning": "명령하다", "reading": "령"},
    {"hanja": "特", "meaning": "특별하다", "reading": "특"},
    {"hanja": "洗", "meaning": "씻다", "reading": "세"},
    {"hanja": "滿", "meaning": "차다", "reading": "만"},
    {"hanja": "忠", "meaning": "차다", "reading": "충"},
    {"hanja": "豐", "meaning": "풍성하다", "reading": "풍"},
    {"hanja": "考", "meaning": "생각하다", "reading": "고"},
    {"hanja": "想", "meaning": "생각", "reading": "상"},
    {"hanja": "備", "meaning": "갖추다", "reading": "비"},
    {"hanja": "保", "meaning": "지키다", "reading": "보"},
    {"hanja": "守", "meaning": "지키다", "reading": "수"},
    {"hanja": "留", "meaning": "머무르다", "reading": "류"},
    {"hanja": "郡", "meaning": "고을", "reading": "군"},
    {"hanja": "安", "meaning": "편안하다", "reading": "안"},
    {"hanja": "治", "meaning": "다스리다", "reading": "치"},
    {"hanja": "急", "meaning": "급하다", "reading": "급"},
    {"hanja": "請", "meaning": "개다", "reading": "청"},
    {"hanja": "番", "meaning": "차례", "reading": "번"},
    {"hanja": "唯", "meaning": "오직", "reading": "유"},
    {"hanja": "制", "meaning": "차례", "reading": "제"},
    {"hanja": "均", "meaning": "고르다", "reading": "균"},
    {"hanja": "律", "meaning": "법", "reading": "률"},
    {"hanja": "士", "meaning": "선비", "reading": "사"},
    {"hanja": "烈", "meaning": "세차다", "reading": "렬"},
    {"hanja": "志", "meaning": "뜻", "reading": "지"},
    {"hanja": "兵", "meaning": "군사", "reading": "병"},
    {"hanja": "卒", "meaning": "군사", "reading": "졸"}
],
"19과": [
    {"hanja": "愁", "meaning": "근심", "reading": "수"},
    {"hanja": "沙", "meaning": "모래", "reading": "사"},
    {"hanja": "浦", "meaning": "물가", "reading": "포"},
    {"hanja": "腸", "meaning": "창자", "reading": "장"},
    {"hanja": "斷", "meaning": "끊다", "reading": "단"},
    {"hanja": "歸", "meaning": "돌아가다", "reading": "귀"},
    {"hanja": "舟", "meaning": "배", "reading": "주"},
    {"hanja": "喜", "meaning": "기쁘다", "reading": "희"},
    {"hanja": "悲", "meaning": "슬프다", "reading": "비"},
    {"hanja": "悅", "meaning": "기쁘다", "reading": "열"},
    {"hanja": "怒", "meaning": "성내다", "reading": "노"},
    {"hanja": "哀", "meaning": "슬프다", "reading": "애"},
    {"hanja": "惜", "meaning": "아끼다", "reading": "석"},
    {"hanja": "傷", "meaning": "다치다", "reading": "상"},
    {"hanja": "哉", "meaning": "어조사", "reading": "재"},
    {"hanja": "歡", "meaning": "기쁘다", "reading": "환"},
    {"hanja": "迎", "meaning": "맞다", "reading": "영"},
    {"hanja": "送", "meaning": "보내다", "reading": "송"},
    {"hanja": "呼", "meaning": "부르다", "reading": "호"},
    {"hanja": "鳴", "meaning": "울다", "reading": "명"},
    {"hanja": "壯", "meaning": "씩씩하다", "reading": "장"},
    {"hanja": "運", "meaning": "옮기다, 운수", "reading": "운"},
    {"hanja": "鄕", "meaning": "시골", "reading": "향"},
    {"hanja": "京", "meaning": "서울", "reading": "경"},
    {"hanja": "農", "meaning": "농사", "reading": "농"},
    {"hanja": "依", "meaning": "의지하다", "reading": "의"},
    {"hanja": "責", "meaning": "꾸짖다", "reading": "책"},
    {"hanja": "最", "meaning": "가장", "reading": "최"},
    {"hanja": "昌", "meaning": "창성하다", "reading": "창"},
    {"hanja": "驚", "meaning": "놀라다", "reading": "경"},
    {"hanja": "且", "meaning": "또", "reading": "차"},
    {"hanja": "仰", "meaning": "우러르다", "reading": "앙"},
    {"hanja": "笑", "meaning": "웃다", "reading": "소"},
    {"hanja": "詩", "meaning": "글, 시", "reading": "시"},
    {"hanja": "設", "meaning": "말씀", "reading": "설"},
    {"hanja": "散", "meaning": "흩어지다", "reading": "산"},
    {"hanja": "章", "meaning": "글", "reading": "장"}
],
"20과": [
    {"hanja": "與", "meaning": "더불다", "reading": "여"},
    {"hanja": "隋", "meaning": "수나라", "reading": "수"},
    {"hanja": "策", "meaning": "꾀", "reading": "책"},
    {"hanja": "求", "meaning": "연구하다", "reading": "구"},
    {"hanja": "妙", "meaning": "묘하다", "reading": "묘"},
    {"hanja": "數", "meaning": "세다", "reading": "산"},
    {"hanja": "窮", "meaning": "다하다", "reading": "궁"},
    {"hanja": "理", "meaning": "다스리다, 이치", "reading": "리"},
    {"hanja": "戰", "meaning": "싸움", "reading": "전"},
    {"hanja": "勝", "meaning": "이기다", "reading": "승"},
    {"hanja": "功", "meaning": "공", "reading": "공"},
    {"hanja": "既", "meaning": "이미", "reading": "기"},
    {"hanja": "願", "meaning": "원하다", "reading": "원"},
    {"hanja": "云", "meaning": "말하다", "reading": "운"},
    {"hanja": "換", "meaning": "갈다", "reading": "연"},
    {"hanja": "探", "meaning": "찾다", "reading": "탐"},
    {"hanja": "計", "meaning": "세다", "reading": "계"},
    {"hanja": "減", "meaning": "덜다", "reading": "감"},
    {"hanja": "極", "meaning": "다하다", "reading": "극"},
    {"hanja": "甚", "meaning": "심하다", "reading": "심"},
    {"hanja": "貧", "meaning": "가난하다", "reading": "빈"},
    {"hanja": "困", "meaning": "곤하다", "reading": "곤"},
    {"hanja": "柔", "meaning": "부드럽다", "reading": "유"},
    {"hanja": "爭", "meaning": "다투다", "reading": "쟁"},
    {"hanja": "舌", "meaning": "혀", "reading": "설"},
    {"hanja": "停", "meaning": "머무르다", "reading": "정"},
    {"hanja": "法", "meaning": "법", "reading": "법"},
    {"hanja": "冷", "meaning": "차다", "reading": "랭"},
    {"hanja": "投", "meaning": "던지다", "reading": "투"},
    {"hanja": "弓", "meaning": "활", "reading": "궁"},
    {"hanja": "射", "meaning": "쏘다", "reading": "사"},
    {"hanja": "助", "meaning": "돕다", "reading": "조"},
    {"hanja": "着", "meaning": "붙다", "reading": "착"},
    {"hanja": "線", "meaning": "줄", "reading": "선"},
    {"hanja": "半", "meaning": "반", "reading": "반"},
    {"hanja": "圓", "meaning": "둥글다", "reading": "원"},
    {"hanja": "數", "meaning": "세다", "reading": "수"},
    {"hanja": "等", "meaning": "무리, 같다", "reading": "등"},
    {"hanja": "式", "meaning": "법", "reading": "식"}
],
"21과": [
    {"hanja": "尋", "meaning": "찾다", "reading": "심"},
    {"hanja": "隱", "meaning": "숨다", "reading": "은"},
    {"hanja": "遇", "meaning": "만나다", "reading": "우"},
    {"hanja": "松", "meaning": "소나무", "reading": "송"},
    {"hanja": "問", "meaning": "묻다", "reading": "문"},
    {"hanja": "童", "meaning": "아이", "reading": "동"},
    {"hanja": "採", "meaning": "캐다", "reading": "채"},
    {"hanja": "藥", "meaning": "약", "reading": "약"},
    {"hanja": "只", "meaning": "다만", "reading": "지"},
    {"hanja": "此", "meaning": "이", "reading": "차"},
    {"hanja": "深", "meaning": "깊다", "reading": "심"},
    {"hanja": "處", "meaning": "곳", "reading": "처"},
    {"hanja": "答", "meaning": "대답하다", "reading": "답"},
    {"hanja": "訪", "meaning": "찾다", "reading": "방"},
    {"hanja": "時", "meaning": "때", "reading": "시"},
    {"hanja": "空", "meaning": "비다", "reading": "공"},
    {"hanja": "開", "meaning": "열다", "reading": "개"},
    {"hanja": "再", "meaning": "다시", "reading": "재"},
    {"hanja": "閉", "meaning": "닫다", "reading": "폐"},
    {"hanja": "業", "meaning": "일", "reading": "업"},
    {"hanja": "場", "meaning": "마당", "reading": "장"},
    {"hanja": "閑", "meaning": "한가하다", "reading": "한"},
    {"hanja": "忙", "meaning": "바쁘다", "reading": "망"},
    {"hanja": "期", "meaning": "기약하다", "reading": "기"},
    {"hanja": "兒", "meaning": "아이", "reading": "아"},
    {"hanja": "單", "meaning": "다만", "reading": "단"},
    {"hanja": "堅", "meaning": "굳다", "reading": "견"},
    {"hanja": "固", "meaning": "굳다", "reading": "고"},
    {"hanja": "彼", "meaning": "저", "reading": "피"},
    {"hanja": "天", "meaning": "알다", "reading": "천"},
    {"hanja": "否", "meaning": "아니다", "reading": "부"},
    {"hanja": "幼", "meaning": "어리다", "reading": "유"},
    {"hanja": "蟲", "meaning": "벌레", "reading": "충"},
    {"hanja": "眠", "meaning": "자다", "reading": "면"},
    {"hanja": "脫", "meaning": "벗다", "reading": "탈"},
    {"hanja": "皮", "meaning": "가죽", "reading": "피"},
    {"hanja": "加", "meaning": "더하다", "reading": "가"},
    {"hanja": "道", "meaning": "법도", "reading": "도"},
    {"hanja": "混", "meaning": "섞다", "reading": "혼"},
    {"hanja": "物", "meaning": "물건", "reading": "물"}
],
"22과": [
    {"hanja": "主", "meaning": "주인", "reading": "주"},
    {"hanja": "曰", "meaning": "말하다", "reading": "왈"},
    {"hanja": "王", "meaning": "임금", "reading": "왕"},
    {"hanja": "常", "meaning": "항상", "reading": "상"},
    {"hanja": "汝", "meaning": "너", "reading": "여"},
    {"hanja": "婦", "meaning": "아내", "reading": "부"},
    {"hanja": "今", "meaning": "이제", "reading": "금"},
    {"hanja": "改", "meaning": "고치다", "reading": "개"},
    {"hanja": "乎", "meaning": "어조사", "reading": "호"},
    {"hanja": "匹", "meaning": "짝", "reading": "필"},
    {"hanja": "猶", "meaning": "오히려", "reading": "유"},
    {"hanja": "況", "meaning": "하물며", "reading": "황"},
    {"hanja": "服", "meaning": "옷", "reading": "복"},
    {"hanja": "布", "meaning": "베", "reading": "포"},
    {"hanja": "宿", "meaning": "자다", "reading": "숙"},
    {"hanja": "給", "meaning": "주다", "reading": "급"},
    {"hanja": "穀", "meaning": "곡식", "reading": "곡"},
    {"hanja": "菜", "meaning": "나물", "reading": "채"},
    {"hanja": "住", "meaning": "살다", "reading": "주"},
    {"hanja": "居", "meaning": "살다", "reading": "거"},
    {"hanja": "移", "meaning": "옮기다", "reading": "이"},
    {"hanja": "宅", "meaning": "집", "reading": "택"},
    {"hanja": "街", "meaning": "거리", "reading": "가"},
    {"hanja": "恒", "meaning": "항상", "reading": "항"},
    {"hanja": "幾", "meaning": "몇", "reading": "기"},
    {"hanja": "革", "meaning": "가죽, 바꾸다", "reading": "혁"},
    {"hanja": "昔", "meaning": "예", "reading": "석"},
    {"hanja": "陰", "meaning": "그늘", "reading": "음"},
    {"hanja": "起", "meaning": "일어나다", "reading": "기"},
    {"hanja": "伏", "meaning": "엎드리다", "reading": "복"},
    {"hanja": "許", "meaning": "허락하다", "reading": "허"},
    {"hanja": "容", "meaning": "얼굴, 받아들이다", "reading": "용"},
    {"hanja": "禁", "meaning": "금하다", "reading": "금"},
    {"hanja": "往", "meaning": "가다", "reading": "왕"},
    {"hanja": "片", "meaning": "조각", "reading": "편"},
    {"hanja": "市", "meaning": "시장", "reading": "시"},
    {"hanja": "村", "meaning": "마을", "reading": "촌"},
    {"hanja": "枝", "meaning": "가지", "reading": "지"},
    {"hanja": "葉", "meaning": "잎", "reading": "엽"},
    {"hanja": "基", "meaning": "터", "reading": "기"}
],
"23과": [
    {"hanja": "向", "meaning": "향하다", "reading": "향"},
    {"hanja": "其", "meaning": "그", "reading": "기"},
    {"hanja": "寺", "meaning": "절", "reading": "사"},
    {"hanja": "唱", "meaning": "부르다", "reading": "창"},
    {"hanja": "君", "meaning": "임금", "reading": "군"},
    {"hanja": "驢", "meaning": "당나귀", "reading": "려"},
    {"hanja": "吹", "meaning": "불다", "reading": "취"},
    {"hanja": "聲", "meaning": "소리", "reading": "성"},
    {"hanja": "冊", "meaning": "책", "reading": "책"},
    {"hanja": "房", "meaning": "방", "reading": "방"},
    {"hanja": "典", "meaning": "법, 책", "reading": "전"},
    {"hanja": "經", "meaning": "글", "reading": "경"},
    {"hanja": "卷", "meaning": "책", "reading": "권"},
    {"hanja": "篇", "meaning": "책", "reading": "편"},
    {"hanja": "怨", "meaning": "원망하다", "reading": "원"},
    {"hanja": "恨", "meaning": "한하다", "reading": "한"},
    {"hanja": "惠", "meaning": "은혜", "reading": "혜"},
    {"hanja": "憂", "meaning": "근심", "reading": "우"},
    {"hanja": "患", "meaning": "근심", "reading": "환"},
    {"hanja": "解", "meaning": "풀다", "reading": "해"},
    {"hanja": "消", "meaning": "사라지다", "reading": "소"},
    {"hanja": "植", "meaning": "심다", "reading": "식"},
    {"hanja": "栽", "meaning": "심다", "reading": "재"},
    {"hanja": "勤", "meaning": "부지런하다", "reading": "근"},
    {"hanja": "勉", "meaning": "힘쓰다", "reading": "면"},
    {"hanja": "練", "meaning": "익히다", "reading": "련"},
    {"hanja": "接", "meaning": "잇다", "reading": "접"},
    {"hanja": "續", "meaning": "잇다", "reading": "속"},
    {"hanja": "條", "meaning": "조목", "reading": "과"},
    {"hanja": "擧", "meaning": "들다", "reading": "거"},
    {"hanja": "仙", "meaning": "신선하다", "reading": "선"},
    {"hanja": "造", "meaning": "만들다", "reading": "조"},
    {"hanja": "扶", "meaning": "돕다", "reading": "부"},
    {"hanja": "浮", "meaning": "뜨다", "reading": "부"},
    {"hanja": "揚", "meaning": "날리다", "reading": "양"},
    {"hanja": "景", "meaning": "볕", "reading": "경"},
    {"hanja": "氣", "meaning": "기운", "reading": "기"},
    {"hanja": "競", "meaning": "다투다", "reading": "경"},
    {"hanja": "技", "meaning": "재주", "reading": "기"}
],
"24과": [
    {"hanja": "德", "meaning": "덕", "reading": "덕"},
    {"hanja": "捐", "meaning": "버리다", "reading": "연"},
    {"hanja": "貿", "meaning": "무역하다", "reading": "무"},
    {"hanja": "米", "meaning": "쌀", "reading": "미"},
    {"hanja": "取", "meaning": "가지다", "reading": "취"},
    {"hanja": "余", "meaning": "남다", "reading": "여"},
    {"hanja": "授", "meaning": "보내다", "reading": "수"},
    {"hanja": "官", "meaning": "벼슬", "reading": "관"},
    {"hanja": "集", "meaning": "모으다", "reading": "집"},
    {"hanja": "庭", "meaning": "뜰", "reading": "정"},
    {"hanja": "店", "meaning": "가게", "reading": "점"},
    {"hanja": "酒", "meaning": "술", "reading": "주"},
    {"hanja": "商", "meaning": "장사", "reading": "상"},
    {"hanja": "飯", "meaning": "밥", "reading": "반"},
    {"hanja": "堂", "meaning": "집", "reading": "당"},
    {"hanja": "講", "meaning": "익히다", "reading": "강"},
    {"hanja": "佛", "meaning": "부처", "reading": "불"},
    {"hanja": "舍", "meaning": "집", "reading": "사"},
    {"hanja": "室", "meaning": "집", "reading": "실"},
    {"hanja": "浴", "meaning": "목욕하다", "reading": "욕"},
    {"hanja": "臥", "meaning": "눕다", "reading": "와"},
    {"hanja": "退", "meaning": "물러나다", "reading": "퇴"},
    {"hanja": "錢", "meaning": "돈", "reading": "전"},
    {"hanja": "賞", "meaning": "상 주다", "reading": "상"},
    {"hanja": "積", "meaning": "쌓다", "reading": "저"},
    {"hanja": "元", "meaning": "으뜸", "reading": "원"},
    {"hanja": "課", "meaning": "매기다", "reading": "과"},
    {"hanja": "設", "meaning": "베풀다", "reading": "설"},
    {"hanja": "再", "meaning": "다시", "reading": "갱"},
    {"hanja": "郎", "meaning": "사내", "reading": "랑"},
    {"hanja": "英", "meaning": "꽃부리", "reading": "영"},
    {"hanja": "雄", "meaning": "수컷", "reading": "웅"},
    {"hanja": "正", "meaning": "곧다", "reading": "정"},
    {"hanja": "淑", "meaning": "맑다", "reading": "숙"},
    {"hanja": "賣", "meaning": "팔다", "reading": "매"},
    {"hanja": "買", "meaning": "사다", "reading": "매"},
    {"hanja": "奉", "meaning": "받들다", "reading": "봉"},
    {"hanja": "事", "meaning": "섬기다", "reading": "사"},
    {"hanja": "招", "meaning": "부르다", "reading": "초"},
    {"hanja": "請", "meaning": "청하다", "reading": "청"}
],
"25과": [
    {"hanja": "罕", "meaning": "드물다", "reading": "한"},
    {"hanja": "貪", "meaning": "탐하다", "reading": "탐"},
    {"hanja": "寶", "meaning": "보배", "reading": "보"},
    {"hanja": "爾", "meaning": "너", "reading": "이"},
    {"hanja": "玉", "meaning": "구슬", "reading": "옥"},
    {"hanja": "若", "meaning": "같다", "reading": "약"},
    {"hanja": "瓦", "meaning": "기와", "reading": "와"},
    {"hanja": "印", "meaning": "도장", "reading": "인"},
    {"hanja": "盃", "meaning": "잔", "reading": "배"},
    {"hanja": "柳", "meaning": "버들", "reading": "류"},
    {"hanja": "案", "meaning": "책상", "reading": "안"},
    {"hanja": "浪", "meaning": "물결", "reading": "랑"},
    {"hanja": "煙", "meaning": "연기", "reading": "연"},
    {"hanja": "墨", "meaning": "먹", "reading": "묵"},
    {"hanja": "鍾", "meaning": "쇠북", "reading": "종"},
    {"hanja": "材", "meaning": "재목", "reading": "재"},
    {"hanja": "財", "meaning": "재물", "reading": "재"},
    {"hanja": "貨", "meaning": "재물", "reading": "화"},
    {"hanja": "茂", "meaning": "무성하다", "reading": "무"},
    {"hanja": "盛", "meaning": "성하다", "reading": "성"},
    {"hanja": "尙", "meaning": "오히려, 높이다", "reading": "상"},
    {"hanja": "免", "meaning": "면하다", "reading": "면"},
    {"hanja": "除", "meaning": "덜다", "reading": "제"},
    {"hanja": "素", "meaning": "본디", "reading": "소"},
    {"hanja": "朴", "meaning": "순박하다", "reading": "박"},
    {"hanja": "建", "meaning": "세우다", "reading": "건"},
    {"hanja": "亦", "meaning": "또", "reading": "역"},
    {"hanja": "即", "meaning": "곧", "reading": "즉"},
    {"hanja": "追", "meaning": "쫓다", "reading": "추"},
    {"hanja": "憶", "meaning": "생각하다", "reading": "억"},
    {"hanja": "吟", "meaning": "읊다", "reading": "음"},
    {"hanja": "味", "meaning": "맛", "reading": "미"},
    {"hanja": "賀", "meaning": "하례하다", "reading": "하"},
    {"hanja": "富", "meaning": "부유하다", "reading": "부"},
    {"hanja": "貴", "meaning": "귀하다", "reading": "귀"},
    {"hanja": "榮", "meaning": "영화롭다", "reading": "영"},
    {"hanja": "華", "meaning": "빛나다", "reading": "화"}
]
}
